#!/bin/bash

# activate tmux conda environment
conda activate tmux

# create a new tmux window
tmux new -s EnaUpload

# request an interactive session
srun --partition defq --cpus-per-task 1 --mem 50g --time 48:00:00 --pty bash

# move to the location of the files to be uploaded
cd /gpfs01/home/mbzlld/data/stickleback/cist_fqs

# upload the files with curl
curl --upload-file Cist_16001_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16001_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16002_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16002_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16003_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16003_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16004_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16004_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16005_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16005_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16007_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16007_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16008_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16008_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16009_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16009_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16010_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16010_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16011_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16011_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16013_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16013_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16014_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16014_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16015_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16015_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16016_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16016_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16017_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16017_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16018_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16018_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16020_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16020_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16022_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16022_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16023_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16023_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16027_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16027_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16030_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16030_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16031_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16031_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16034_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16034_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16035_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16035_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16036_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16036_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16038_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16038_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16039_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16039_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16040_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16040_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16044_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16044_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16045_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16045_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16046_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16046_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16048_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16048_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16049_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16049_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16050_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16050_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16051_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16051_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16052_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16052_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16053_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16053_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16054_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16054_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16055_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16055_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16056_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16056_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16057_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16057_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16059_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16059_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16060_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16060_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16061_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16061_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16062_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16062_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16066_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16066_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16067_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16067_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16068_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16068_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16069_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16069_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16070_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16070_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16072_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16072_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16077_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16077_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16078_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16078_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16079_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16079_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16081_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16081_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16082_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16082_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16083_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16083_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16084_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16084_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16085_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16085_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16087_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16087_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16088_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16088_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16090_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16090_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16091_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16091_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16092_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16092_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16093_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16093_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16094_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16094_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16098_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16098_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16099_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16099_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16100_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16100_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16101_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16101_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16102_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16102_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16103_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16103_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16105_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16105_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16106_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16106_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16107_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16107_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16108_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16108_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16109_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16109_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16110_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16110_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16111_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16111_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16112_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16112_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16113_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16113_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16116_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16116_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16117_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16117_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16118_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16118_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16119_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16119_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16120_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16120_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16121_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16121_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16122_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16122_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16123_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16123_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16124_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16124_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16125_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16125_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16126_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16126_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16127_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16127_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16128_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16128_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16129_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16129_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16130_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16130_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16131_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16131_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16132_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_16132_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_B12_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_B12_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_C12_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_C12_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_D12_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_D12_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_E11_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_E11_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_E12_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_E12_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_F11_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_F11_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_G11_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_G11_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_G12_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_G12_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_H11_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_H11_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_H12_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_3_H12_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A1_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A1_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A2_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A2_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_A6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B2_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B2_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_B6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C1_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C1_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C2_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C2_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_C6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D1_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D1_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D7_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_D7_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E1_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E1_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E2_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E2_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E7_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_E7_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F2_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F2_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F7_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_F7_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G1_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G1_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G7_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_G7_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H2_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H2_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H3_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H3_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H4_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H4_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H5_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H5_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H6_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H6_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H7_R1.fq.gz --user username:password ftp://webin2.ebi.ac.uk
curl --upload-file Cist_4_H7_R2.fq.gz --user username:password ftp://webin2.ebi.ac.uk


